#!/usr/bin/env python3
"""Build the LIBRA schema-impact matrix: one CSV row per payload field, across every schema it
has to pass through, plus the change each schema needs.

    libra_field, jsonpath, container,
    funcapp_xhibit_status, funcapp_libra_action, canonical_field, canonical_status,
    pcfdlrm_field, pcfdlrm_status, progression_field, progression_status,
    change_required, change_type, change_detail, tier, notes

The four schema tiers a migrated case crosses, in order:

    FUNC-APP    stagingdlrm-azure-functions/src/main/resources — the gate that validates case.json
                before anything is enqueued. Shallow: it constrains caseDetails and the manifest
                only, and its objects are mostly OPEN, so it rejects on missing `required` fields
                rather than on unknown ones.
                Two columns, because the func-app is gaining a SECOND schema rather than changing
                its one: `funcapp_xhibit_status` is what the existing hardwired XHIBIT schema
                enforces today (it stays exactly as it is), and `funcapp_libra_action` is what the
                new source-system-selected LIBRA schema should do with the field. The XHIBIT column
                is the baseline you author the LIBRA one against — its `required` entries are
                precisely what a copy-paste of the XHIBIT file would wrongly demand of LIBRA.
    CANONICAL   stagingdlrm-domain-value-schema — what the command API actually enforces. Deep and
                CLOSED (additionalProperties:false), so a novel LIBRA field must be added here
                explicitly or the submission is rejected as a terminal, non-retryable 4xx.
    PCFDLRM     cpp-context-prosecution-casefile-dlrm — the downstream consumer. A field the
                canonical schema accepts but PCFDLRM does not model is write-only.
    PROGRESSION reached through the shared core case model (cpp.platform.core.domain
                criminal-court-public-model, rooted at apiProsecutionCase.json). A core field that
                is not reachable from that root is not part of the model a migrated case travels.

XHIBIT has no column: it is already in production, so every field the canonical schema carries
today demonstrably flows end to end. Those rows read `already_flowing` on the downstream columns,
and the interesting rows are the ones where LIBRA and the canonical schema disagree.

Joined on JSONPath (not on definition name), so structurally-equivalent fields line up even where
the schemas organise their `definitions` differently. Rooted at `$.migratedCase`: the
submission-envelope fields the Function App assembles from manifest.json / the blob path
(`submissionId`, `metadata`, `materials`, `channel`, `azureLocation`) are out of scope.

Inputs — generated by the sibling scripts, or read straight from the repos:
    schema/libra/dlrm-libra-0.13.json                       <- generate-dlrm-schema.py
    schema/canonical/staging-dlrm-canonical-flattened.json  <- flatten-canonical-schema.py
    schema/canonical/staging-dlrm-funcapp-flattened.json    <- flatten-canonical-schema.py
    ~/work/repo/cpp-context-prosecution-casefile-dlrm       <- --pcfdlrm
    ~/work/repo/cpp-context-progression                     <- --progression
    ~/work/repo/cpp.platform.core.domain                    <- --core

The PCFDLRM/core mapping for the LIBRA-added fields is hand-curated in MAPPING below — deciding
that LIBRA's `licenseCode` is PCFDLRM's `driverLicenceCode` is a judgement, not something a name
match can establish. Every curated claim is VERIFIED against the checkouts on each run, so the
table cannot silently rot: if a claimed field stops existing, this script fails loudly. Reads
sibling repo checkouts, never Maven artefacts; degrades to unverified output with a warning if a
repo is missing.

Usage:
    python3 tools/schema-gen/build-schema-impact.py                 # markdown table to stdout
    python3 tools/schema-gen/build-schema-impact.py --format csv    # CSV to stdout
    python3 tools/schema-gen/build-schema-impact.py --out           # CSV to the default path,
                                                                    # UTF-8 BOM for Excel
    # just the work list:
    python3 tools/schema-gen/build-schema-impact.py --changes-only --format csv

No cell is left blank except `notes`: a column that does not apply to a row says so explicitly
(`n/a`, or `n/a-already-in-canonical` for `tier`) rather than being empty, so a deliberate answer
cannot be misread as missing data. See NA_FILLED_COLUMNS.
"""

import argparse
import csv
import json
import os
import re
import sys
from collections import OrderedDict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
ANALYSIS = REPO / "docs/analysis/libra-ingestion"
DEFAULT_LIBRA = ANALYSIS / "schema/libra/dlrm-libra-0.13.json"
DEFAULT_CANONICAL = ANALYSIS / "schema/canonical/staging-dlrm-canonical-flattened.json"
DEFAULT_FUNCAPP = ANALYSIS / "schema/canonical/staging-dlrm-funcapp-flattened.json"
DEFAULT_NAME = "libra-schema-impact.csv"

PCFDLRM = Path(os.path.expanduser("~/work/repo/cpp-context-prosecution-casefile-dlrm"))
PROGRESSION = Path(os.path.expanduser("~/work/repo/cpp-context-progression"))
PCF_SCHEMA = PCFDLRM / "pcfdlrm-domain/pcfdlrm-domain-value-schema/src/main/resources/json/schema"

# The core domain repo holds the schemas Progression and the other contexts actually contract on:
# criminal-court-public-model is Progression's inbound case model, and common-core-domain is the
# justice.gov.uk/domain/core/common/definitions.json that everything $refs. Evidence from HERE is
# authoritative; the cpp-context-progression checkout only carries query/command views and
# fixtures, so it is used as a fallback signal.
CORE = Path(os.path.expanduser("~/work/repo/cpp.platform.core.domain"))

ROOT_PROPERTY = "migratedCase"

# Envelope fields assembled by the Function App from manifest.json / the blob path — excluded.
ENVELOPE_FIELDS = {"submissionId", "metadata", "materials", "channel", "azureLocation"}

CONSTRAINT_KEYS = ["$ref", "type", "maxLength", "minLength", "maximum", "minimum", "pattern",
                   "enum", "minItems"]

# Previously date/dateTime/uuid had to be compared by ref name, because the flattened canonical
# schema could only stub them. flatten-canonical-schema.py now resolves them for real from the
# core-domain repo, so they are compared by pattern like everything else. Kept as an empty set so
# a primitive can be made opaque again if a future one genuinely cannot be resolved.
OPAQUE_REFS = set()

# Same concept, different property name: LIBRA supplies a reference-data code where the canonical
# schema expects a resolved UUID. Keyed by (parent jsonpath, canonical name) -> LIBRA name.
RENAMES = {
    ("$.migratedCase.defendants[*].offences[*].plea", "id"): "pleaCode",
    ("$.migratedCase.defendants[*].offences[*].verdict", "id"): "verdictCode",
    ("$.migratedCase.defendants[*].offences[*].allocationDecision", "motReasonId"):
        "allocationDecisionCode",
}

# --- canonical_status ---------------------------------------------------------------------
CANON_SAME = "exists_same_constraint"
CANON_CONSTRAINT = "exists_different_constraint"
CANON_REQ_CANONICAL = "exists_optional_in_libra_required_in_canonical"
CANON_REQ_LIBRA = "exists_required_in_libra_optional_in_canonical"
CANON_RENAMED = "exists_renamed_and_retyped"
CANON_ABSENT_LIBRA = "not_in_libra"
CANON_ADDED = "added_not_in_canonical"

# --- funcapp_xhibit_status: what the live, hardwired XHIBIT gate enforces today -----------
FUNC_REQUIRED = "required"
FUNC_OPTIONAL = "optional"
FUNC_REJECTED = "rejected_as_additional"    # absent, and the enclosing object is closed
FUNC_NOT_VALIDATED = "not_validated"        # the XHIBIT schema never reaches this field

# --- funcapp_libra_action: what the NEW LIBRA gate schema should do with the field --------
# Derived from the generated LIBRA schema, so it follows the workbook rather than presuming
# anything. `declare` is load-bearing, not cosmetic: the generated LIBRA caseDetails is CLOSED
# (additionalProperties:false) where the XHIBIT gate's is open, so a LIBRA field left undeclared
# is rejected there rather than passed through.
GATE_REQUIRE = "require"                    # LIBRA supplies it, mandatory for every case type
GATE_DECLARE = "declare"                    # LIBRA supplies it, optional or conditionally mandatory
GATE_OMIT = "omit"                          # LIBRA never supplies it — must not be declared/required
GATE_OUT_OF_SCOPE = "not-validated-at-gate"  # below the depth this gate validates

# How deep the LIBRA gate schema is assumed to validate. `case-details` mirrors the depth the
# XHIBIT gate uses today (its migratedCase declares caseDetails and nothing else) and is the
# default, because keeping the two gates symmetrical is the status quo and the conservative
# reading. `full` assumes the generated LIBRA schema is used at its own depth — 113 leaves against
# the XHIBIT gate's 8 — which buys earlier rejection at the cost of turning every blank or `TBC`
# Format cell in the workbook into a false rejection at the cheapest, least diagnosable point in
# the chain. That trade-off is a story decision (DD-43082), so it is a flag, not a constant.
GATE_DEPTHS = {
    "case-details": ("$.migratedCase.caseDetails",),
    "full": ("$.migratedCase",),
}
DEFAULT_GATE_DEPTH = "case-details"

# --- pcfdlrm_status / progression_status -------------------------------------------------
DOWN_FLOWING = "already_flowing"            # pcfdlrm column only: XHIBIT ships it today
DOWN_EXISTS = "exists_same_name"
DOWN_RENAMED = "exists_different_name"
DOWN_MISSING = "no_field"
DOWN_UNVERIFIED = "unverified"

# progression_status — derived PURELY from the payload schema, never from code.
#   exists_mandatory  in the payload closure AND in its object's `required` list. Means "mandatory
#                     if that object is sent at all" — NOT "the pipeline is broken today".
#   exists_optional   in the payload closure, not required.
#   no_field          not known there under this name: genuinely absent, unreachable from the
#                     payload root, or a naming mismatch this table does not resolve.
# Whether pcfdlrm's converters actually populate the field is a code question, deliberately out of
# scope here (it needs converter scanning, and setter-name matching proved unreliable).
# Existing canonical fields are ASSUMED to flow: XHIBIT is in production and they are already in
# the schema, so whether each one lands in Progression is pre-existing behaviour, not something
# LIBRA changes. Named `assumed_` and not `already_` on purpose — it is an assumption, not a
# verified claim (see the doc's footnote on the three fields pcfdlrm has no counterpart for).
PROG_ASSUMED = "assumed_flowing"
PROG_MANDATORY = "exists_mandatory"
PROG_OPTIONAL = "exists_optional"
PROG_NONE = "no_field"

# The payload pcfdlrm actually sends Progression: command `progression.initiate-court-proceedings`,
# type uk.gov.justice.core.courts.InitiateCourtProceedings = {id, CourtReferral} — so courtReferral
# is the root and everything is drilled down from it.
#
# NOT apiProsecutionCase.json. criminal-court-public-model carries two parallel families: the
# external `api*` read model under external/global/ (id .../core/courts/external/...) and the
# internal command model under global/ (id .../core/courts/...). Only the latter is on this path,
# and the two closures are disjoint.
PROGRESSION_ROOT = "courtReferral.json"

# --- change_type -------------------------------------------------------------------------
# Ordered loosely by how much of the pipeline the change touches. `change_required` is "no" only
# for NONE, LIBRA_RULE and DEFER — filter on it to get the work list.
CH_NONE = "none"
CH_LIBRA_RULE = "libra-rule-only"           # schema already permits it; rule belongs in LIBRA's
CH_RELAX_REQUIRED = "relax-required"
CH_RELAX_COMBINATOR = "relax-combinator"    # an anyOf/oneOf required-branch LIBRA cannot satisfy
CH_RELAX_ENUM = "relax-enum"
CH_RELAX_CONSTRAINT = "relax-constraint"
CH_REVIEW_CONSTRAINT = "review-constraint"  # differs in a way no rule here can adjudicate
CH_MAP_RENAME = "map-rename"
CH_ADD_FIELD = "add-optional-field"
CH_ADD_BLOCKED = "add-field-blocked-downstream"
CH_DEFER = "defer"
CH_DECLARE_ONLY = "declare-only"            # nothing downstream models it, but the payload carries
                                            # it into a CLOSED object, so it cannot just be ignored

NO_CHANGE_TYPES = {CH_NONE, CH_LIBRA_RULE, CH_DEFER}

# The guard sentence every relaxation carries. Relaxing a shared schema silently removes the
# check XHIBIT relies on today, so the constraint has to be re-imposed per source system in the
# validation-rules strategy — this is the single most repeated consequence in the whole matrix.
GUARD_TAIL = ("relaxing the shared schema drops this check for XHIBIT too — re-impose it in the "
              "XHIBIT validation rules keyed on migrationSourceSystemName")
GUARD = f"Guard: {GUARD_TAIL}"

T1 = "1-drop-in"
T2 = "2-renamed"
T3 = "3-officer-pcfdlrm-gap"
T4 = "4-pcfdlrm-gap"
T5 = "5-no-downstream-home"
TIER_ORDER = {T1: 0, T2: 1, T3: 2, T4: 3, T5: 4, "": 5}

# Structurally-empty cells are filled with an explicit sentinel before output. A blank in a
# spreadsheet reads as "not filled in" as readily as "does not apply", and Excel's filter shows it
# as (Blanks) either way — which for these columns would misrepresent a deliberate answer as
# missing data. Only the four field-NAME columns get the bare marker: each sits next to a status
# column that already states the reason (already_flowing, no_field, not_in_libra,
# added_not_in_canonical), so repeating it here would be redundant. `tier` has no adjacent status
# of its own, so its filler is self-describing. `notes` is optional prose and stays blank.
NA = "n/a"
TIER_NA = "n/a-already-in-canonical"
NA_FILLED_COLUMNS = ("libra_field", "canonical_field", "pcfdlrm_field", "progression_field")

# libra_field -> (tier, pcfdlrm field, pcfdlrm file, core field, core file, recommendation)
# "" means "no counterpart found". PCFDLRM files are relative to PCF_SCHEMA; core files are
# basenames within cpp.platform.core.domain (criminal-court-public-model unless noted).
MAPPING = {
    # --- Tier 1: same name in PCFDLRM, drop-in as an optional canonical field ------------
    "statementOfFacts":       (T1, "statementOfFacts", "migrated/migrated-offence.json",
                               "statementOfFacts", "prosecutionCase.json",
                               "Add to offence as optional; identical in PCFDLRM. NOTE core holds it at CASE level, not per offence — multi-offence LIBRA text collapses at the Progression hop"),
    "statementOfFactsWelsh":  (T1, "statementOfFactsWelsh", "migrated/migrated-offence.json",
                               "statementOfFactsWelsh", "prosecutionCase.json",
                               "Add to offence as optional; identical in PCFDLRM. Core holds it at CASE level"),
    "backDuty":               (T1, "backDuty", "migrated/migrated-offence.json", "", "",
                               "Add to offence as optional; drop the generator's minimum:0. Core has backDuty only in sjp-public-model/financialPenalty.json and discharge.json, neither reachable from the courtReferral payload"),
    "backDutyDateFrom":       (T1, "backDutyDateFrom", "migrated/migrated-offence.json", "", "",
                               "Add to offence as optional; $ref date, identical in PCFDLRM. No core case-model field"),
    "backDutyDateTo":         (T1, "backDutyDateTo", "migrated/migrated-offence.json", "", "",
                               "Add to offence as optional; $ref date, identical in PCFDLRM. No core case-model field"),
    "prosecutorOfferAOCP":    (T1, "prosecutorOfferAOCP", "migrated/migrated-offence.json", "", "",
                               "Add to offence as optional; boolean, identical in PCFDLRM. No core case-model field"),
    "vehicleMake":            (T1, "vehicleMake", "migrated/migrated-offence.json",
                               "vehicleMake", "offenceFacts.json",
                               "Add to offence as optional; core defines the type as string maxLength 60 — exactly the sheet's A60. Reaches Progression via offence.offenceFacts. NOTE this was previously recorded as dying at PCFDLRM; that rested on rooting reachability at the external apiProsecutionCase model instead of the courtReferral payload"),
    "vehicleRegistrationMark": (T1, "vehicleRegistrationMark", "migrated/migrated-offence.json",
                               "vehicleRegistration", "offenceFacts.json",
                               "Add to offence as optional; use the core $ref (maxLength 11 + pattern) PCFDLRM uses. Core renames it vehicleRegistration under offenceFacts"),
    "vehicleCode":            (T1, "vehicleCode", "vehicle-related-offence.json",
                               "vehicleCode", "offenceFacts.json",
                               "Add to offence as optional; PCFDLRM groups it under vehicleRelatedOffence, core under offenceFacts"),
    "driverNumber":           (T1, "driverNumber", "individual.json",
                               "driverNumber", "personDefendant.json",
                               "Add to INDIVIDUAL (not defendant) as optional; identical in PCFDLRM, live in core"),
    "nationalInsuranceNumber": (T1, "nationalInsuranceNumber", "individual.json",
                               "nationalInsuranceNumber", "person.json",
                               "Add to INDIVIDUAL as optional — stagingDLRM's own pcf-definitions.json already defines the pattern but references it nowhere, so this is a one-line $ref. Live end to end"),
    "occupation":             (T1, "occupation", "personal-information.json",
                               "occupation", "person.json",
                               "Add to PERSONAL-INFORMATION (not defendant) as optional; identical in PCFDLRM, live in core"),
    "additionalNationality":  (T1, "additionalNationality", "self-defined-information.json",
                               "additionalNationalityCode", "person.json",
                               "Add to selfDefinedInformation as optional; identical in PCFDLRM. Core names it additionalNationalityCode (also has Id/Description)"),
    "summonsCode":            (T1, "summonsCode", "case-details.json",
                               "summonsCode", "prosecutionCase.json",
                               "Add to caseDetails as optional; live end to end"),
    # --- Tier 2: exists downstream under a different name --------------------------------
    "licenseCode":            (T2, "driverLicenceCode", "individual.json",
                               "driverLicenceCode", "personDefendant.json",
                               "Add to individual as optional, named driverLicenceCode to match both PCFDLRM and core; note both also carry driverLicence/LicenseIssue"),
    "defendantOccupationCode": (T2, "occupationCode", "personal-information.json",
                               "occupationCode", "person.json",
                               "Add to personalInformation as optional, named occupationCode to match PCFDLRM and core"),
    "middleName2":            (T2, "givenName3", "personal-information.json", "", "",
                               "Maps to PCFDLRM givenName3 (maxLength 35 vs the sheet's 255), but no reachable core schema has a third given name (person.json has one middleName) — lost at the PCFDLRM->Progression hop"),
    "prosecutorCompensation": (T2, "appliedCompensation", "migrated/migrated-offence.json", "", "",
                               "Likely PCFDLRM appliedCompensation (number both sides) — CONFIRM semantics. No core case-model field"),
    # --- Tier 3: officerInCase — LIVE in core, the gap is PCFDLRM ------------------------
    "policeOfficerRank":      (T3, "policeOfficerRank", "pcf-policeOfficerInCase.json",
                               "policeOfficerRank", "policeOfficerInCase.json",
                               "REQUIRED in core's officer block. PCFDLRM has the field but its officer schema is referenced by nothing — PCFDLRM must wire it up"),
    "policeWorkerReferenceNumber": (T3, "", "",
                               "policeWorkerReferenceNumber", "policeOfficerInCase.json",
                               "REQUIRED in core's officer block but absent from PCFDLRM — PCFDLRM needs the field added"),
    "policeWorkerLocationCode": (T3, "", "",
                               "policeWorkerLocationCode", "policeOfficerInCase.json",
                               "REQUIRED in core's officer block but absent from PCFDLRM — PCFDLRM needs the field added"),
    "forename":               (T3, "personalInformation.firstName", "personal-information.json",
                               "firstName", "person.json",
                               "Officer names travel via personDetails -> apiPerson.firstName"),
    "forename2":              (T3, "personalInformation.givenName2", "personal-information.json",
                               "middleName", "person.json",
                               "Officer second forename -> core person.middleName"),
    "forename3":              (T3, "personalInformation.givenName3", "personal-information.json",
                               "", "",
                               "PCFDLRM has givenName3; core has forename3 only in cpsPersonDefendantDetails.json, which is NOT reachable from the courtReferral payload, and apiPerson has a single middleName — third forename is lost downstream"),
    "surname":                (T3, "personalInformation.lastName", "personal-information.json",
                               "lastName", "person.json",
                               "Officer surname -> core person.lastName (required there)"),
    "address1":               (T3, "address1", "pcf-address.json", "address1", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "address2":               (T3, "address2", "pcf-address.json", "address2", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "address3":               (T3, "address3", "pcf-address.json", "address3", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "address4":               (T3, "address4", "pcf-address.json", "address4", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "address5":               (T3, "address5", "pcf-address.json", "address5", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "postcode":               (T3, "postcode", "pcf-address.json", "postcode", "address.json",
                               "Officer address reuses pcf-address / core address"),
    "workTelephoneNumber":    (T3, "contactDetails.work", "contact-details.json",
                               "work", "contactNumber.json",
                               "Maps onto contactDetails.work / core contactNumber.work"),
    "mobileTelephoneNumber":  (T3, "contactDetails.mobile", "contact-details.json",
                               "mobile", "contactNumber.json",
                               "Maps onto contactDetails.mobile / core contactNumber.mobile"),
    "primaryEmail":           (T3, "contactDetails.primaryEmail", "contact-details.json",
                               "primaryEmail", "contactNumber.json",
                               "Maps onto contactDetails.primaryEmail / core contactNumber.primaryEmail"),
    "secondaryEmail":         (T3, "contactDetails.secondaryEmail", "contact-details.json",
                               "secondaryEmail", "contactNumber.json",
                               "Maps onto contactDetails.secondaryEmail / core contactNumber.secondaryEmail"),
    "faxNumber":              (T3, "", "", "fax", "contactNumber.json",
                               "Core has it as apiContactNumber.fax; PCFDLRM's contact-details has no fax — PCFDLRM needs the field added"),
    "dxAddress":              (T3, "", "", "", "",
                               "No home in the criminal-court model. Only cps-core-domain/contact-details.json has dxAddress, a different domain — defer"),
    "uniquePropertyReferenceNumber": (T3, "", "", "", "",
                               "The ONLY LIBRA field with no counterpart in PCFDLRM or anywhere in the core domain — defer"),
    # --- Tier 4: reachable in the core case model, absent from PCFDLRM -------------------
    "numPreviousConvictions": (T4, "", "",
                               "numberOfPreviousConvictionsCited", "defendant.json",
                               "Live and reachable in core as defendant.numberOfPreviousConvictionsCited (\"number of previous convictions cited by the prosecuting authority\"). Blocked at PCFDLRM, which has no equivalent — same shape as convictionDate"),
    "organisationTelephoneNumber": (T4, "", "",
                               "contact", "organisation.json",
                               "An organisation phone reaches Progression via organisation.contact -> contactNumber (work/home/mobile). Blocked at PCFDLRM. NOTE the workbook already has companyTelephoneNumber (-> defendant.telephoneNumberBusiness) so row 63 looks like a duplicate — confirm before adding either"),
    "convictionDate":         (T4, "", "", "convictionDate", "offence.json",
                               "Live and reachable in core offence, but PCFDLRM's migrated-offence has no convictionDate, so adding it to canonical alone makes it write-only. PCFDLRM must add it first"),
    # --- Tier 5: nothing reachable downstream models it ----------------------------------
    "informant":              (T5, "", "", "", "",
                               "Do not add yet — nothing in PCFDLRM or core. Progression's only `informant` is a $ref to prosecutingAuthority in a generate-summons schema, different semantics"),
    "writtenChargePostingDate": (T5, "", "", "", "",
                               "Do not add yet — no PCFDLRM field. Core's nearest match is sjpReferral.noticeDate, in a file NOT reachable from the courtReferral payload"),
    "prosecutorCosts":        (T5, "", "", "", "",
                               "Do not add yet — no PCFDLRM field. Core has prosecutorCosts only in summons-document-content.json, NOT reachable from the courtReferral payload (summons document text, not the case model)"),
}



# Which core object each canonical container maps onto, taken from the payload object graph rooted
# at courtReferral.json. The name search for an added field is scoped to this rather than the whole
# closure: an unscoped search picks whichever schema happens to sort first, which resolved plea.id
# to bailStatus.json#id and offenceCode to lesserOrAlternativeOffence.json. A field present in an
# unrelated schema is not reachable at THIS position, so scoping is what makes `no_field` mean
# something.
CONTAINER_CORE = {
    "caseDetails":                                     "prosecutionCase.json",
    "caseDetails.prosecutor":                          "prosecutionCaseIdentifier.json",
    "caseDetails.caseMarkers[*]":                      "marker.json",
    "migrationSourceSystem":                           "migrationSourceSystem.json",
    "hearings[*]":                                     "listHearingRequest.json",
    "hearings[*].weekCommencingDate":                  "weekCommencingDate.json",
    "hearings[*].listedDefendants[*]":                 "listDefendantRequest.json",
    "defendants[*]":                                   "defendant.json",
    "defendants[*].address":                           "address.json",
    "defendants[*].individual":                        "personDefendant.json",
    "defendants[*].individual.personalInformation":    "person.json",
    "defendants[*].individual.personalInformation.address":        "address.json",
    "defendants[*].individual.personalInformation.contactDetails": "contactNumber.json",
    "defendants[*].individual.selfDefinedInformation":             "person.json",
    "defendants[*].individualAliases[*]":              "defendantAlias.json",
    "defendants[*].offences[*]":                       "offence.json",
    "defendants[*].offences[*].alcoholRelatedOffence": "offenceFacts.json",
    "defendants[*].offences[*].plea":                  "plea.json",
    "defendants[*].offences[*].verdict":               "verdict.json",
    "defendants[*].offences[*].allocationDecision":    "allocationDecision.json",
    # parent guardian reuses the same core person/organisation/address/contact objects
    "defendants[*].individual.parentGuardianInformation":         "person.json",
    "defendants[*].individual.parentGuardianInformation.address": "address.json",
    "defendants[*].individual.parentGuardianInformation.personalInformation":                "person.json",
    "defendants[*].individual.parentGuardianInformation.personalInformation.address":        "address.json",
    "defendants[*].individual.parentGuardianInformation.personalInformation.contactDetails": "contactNumber.json",
    # the LIBRA-only officer block
    "officerInCase":                                   "policeOfficerInCase.json",
    "officerInCase.address":                           "address.json",
}

# --------------------------------------------------------------------------------------
# Schema walking
# --------------------------------------------------------------------------------------

def deref(node, definitions, depth=0):
    """Follow $ref while the target is a scalar (no properties of its own)."""
    if depth > 8 or not isinstance(node, dict):
        return node
    ref = node.get("$ref")
    if not isinstance(ref, str) or not ref.startswith("#/definitions/"):
        return node
    leaf = ref.split("/")[-1]
    if leaf in OPAQUE_REFS:
        return {"$ref": leaf}
    target = definitions.get(leaf)
    if not isinstance(target, dict) or target.get("properties"):
        return node
    merged = {k: v for k, v in target.items() if k != "description"}
    merged.update({k: v for k, v in node.items() if k not in ("$ref", "description")})
    return deref(merged, definitions, depth + 1)


def object_target(node, definitions):
    """Return (object schema, is_array) if this node leads to an object, else (None, False)."""
    if not isinstance(node, dict):
        return None, False
    is_array = node.get("type") == "array"
    inner = node.get("items", {}) if is_array else node
    if isinstance(inner, dict) and isinstance(inner.get("$ref"), str):
        name = inner["$ref"].split("/")[-1]
        target = definitions.get(name, {})
        if isinstance(target, dict) and (target.get("properties")
                                        or any(k in target for k in ("oneOf", "anyOf"))):
            return target, is_array
        return None, is_array
    if isinstance(inner, dict) and (inner.get("properties")
                                    or any(k in inner for k in ("oneOf", "anyOf"))):
        return inner, is_array
    return None, is_array


def branches(obj):
    """An object plus any oneOf/anyOf branches, so union-typed nodes contribute all their fields."""
    out = [obj]
    for key in ("oneOf", "anyOf"):
        for branch in obj.get(key, []) or []:
            if isinstance(branch, dict):
                out.append(branch)
    return out


def combinator_required(obj):
    """Names demanded by a pure `{"required": [...]}` anyOf/oneOf branch.

    The canonical caseDetails carries `anyOf: [{required:[dateOfCommittal]},
    {required:[dateOfSending]}]` — a blocker that lives in neither `properties` nor the top-level
    `required`, so a matrix that only diffed those two would silently miss it. Returns
    {name: [alternatives]} so each affected leaf can name the other side of the choice.
    """
    groups = []
    for key in ("oneOf", "anyOf"):
        for branch in obj.get(key, []) or []:
            if isinstance(branch, dict) and set(branch) == {"required"}:
                groups.append(list(branch["required"]))
    out = {}
    for group in groups:
        for name in group:
            others = [n for g in groups for n in g if n != name]
            out.setdefault(name, sorted(set(others)))
    return out


def walk(schema, root_property):
    """Return (leaves, objects) keyed by jsonpath.

    leaves[path]  = {name, constraints, ref, array, required, row, alternatives}
    objects[path] = {closed: bool}   — `closed` means additionalProperties:false, i.e. an unknown
                                      field here is rejected rather than ignored.
    """
    definitions = schema.get("definitions", {})
    leaves, objects = OrderedDict(), OrderedDict()

    root = schema.get("properties", {}).get(root_property)
    if root is None:                                  # canonical/func-app root via $ref
        ref = schema.get("$ref")
        entry = definitions.get(ref.split("/")[-1], {}) if isinstance(ref, str) else {}
        root = entry.get("properties", {}).get(root_property)
    if root is None:
        sys.exit(f"error: no {root_property!r} in {schema.get('id')}")

    def descend(node, path, seen):
        obj, is_array = object_target(node, definitions)
        if obj is None:
            return
        marker = f"{path}{'[*]' if is_array else ''}"
        if marker in seen:
            return
        seen = seen | {marker}
        objects[marker] = {"closed": obj.get("additionalProperties") is False}
        alternatives = combinator_required(obj)
        for holder in branches(obj):
            required = set(holder.get("required", []))
            for name, child in (holder.get("properties") or {}).items():
                child_path = f"{marker}.{name}"
                resolved = deref(child, definitions)
                sub, sub_array = object_target(child, definitions)
                if sub is not None:
                    descend(child, child_path, seen)
                    continue
                description = child.get("description", "") or ""
                row = re.search(r"Sheet row (\d+)", description)
                # The generator deliberately does NOT emit an enum for coded fields (a closed Java
                # enum downstream makes a rejection terminal), it records the codes in prose. Pull
                # them back out so a relax-enum row can name the values that have to be allowed.
                values = re.search(r"Documented values: ([^(]+)", description)
                leaves[child_path] = {
                    "name": name,
                    "constraints": {k: resolved[k] for k in CONSTRAINT_KEYS if k in resolved},
                    "ref": (child.get("$ref") or "").split("/")[-1] or None,
                    "array": sub_array or resolved.get("type") == "array",
                    "required": name in required,
                    "row": row.group(1) if row else None,
                    "values": values.group(1).strip().rstrip(".") if values else None,
                    "alternatives": alternatives.get(name),
                }

    descend({"$ref": root.get("$ref")} if root.get("$ref") else root,
            f"${'.' + root_property}", frozenset())
    return leaves, objects


def drop_envelope(store):
    for path in [p for p in store if p.split(".")[1].split("[")[0] in ENVELOPE_FIELDS]:
        del store[path]


# --------------------------------------------------------------------------------------
# Status derivation
# --------------------------------------------------------------------------------------

def canonical_status(canon, libra):
    if libra is None:
        return CANON_ABSENT_LIBRA
    same = canon["constraints"] == libra["constraints"]
    if same and canon["required"] == libra["required"]:
        return CANON_SAME
    if same and canon["required"] and not libra["required"]:
        return CANON_REQ_CANONICAL
    if same and libra["required"] and not canon["required"]:
        return CANON_REQ_LIBRA
    return CANON_CONSTRAINT


def funcapp_xhibit_status(path, func_leaves, func_objects):
    """What the live, hardwired XHIBIT gate schema enforces at this path today."""
    entry = func_leaves.get(path)
    if entry is not None:
        return FUNC_REQUIRED if entry["required"] else FUNC_OPTIONAL
    # Not declared. Whether that matters depends on the enclosing object: the func-app's
    # caseDetails and migratedCase are OPEN, so unknown fields sail through; its
    # migrationSourceSystem and submission root are closed, so they would be rejected.
    parent = path.rpartition(".")[0]
    holder = func_objects.get(parent)
    if holder is None:
        return FUNC_NOT_VALIDATED
    return FUNC_REJECTED if holder["closed"] else FUNC_NOT_VALIDATED


def funcapp_libra_action(path, libra, gate_depth):
    """What the new source-system-selected LIBRA gate schema should do with this field.

    Read off the generated LIBRA schema, so it reflects the workbook and not an assumption about
    the design. XHIBIT's own gate schema is never consulted here — it is not changing.
    """
    if not path.startswith(GATE_DEPTHS[gate_depth]):
        return GATE_OUT_OF_SCOPE
    if libra is None:
        return GATE_OMIT
    return GATE_REQUIRE if libra["required"] else GATE_DECLARE


def libra_constraints(libra):
    """LIBRA's constraints with the known generator artefact removed.

    The generator adds `minimum: 0` to every N<n> integer because the sheet's format code implies
    unsigned; the canonical schema simply omits it. Left in, it reads as "LIBRA allows 0 where
    canonical starts at 1" and invents a relaxation nobody asked for.
    """
    return {k: v for k, v in libra["constraints"].items() if not (k == "minimum" and v == 0)}


def is_generator_artefact(canon, libra):
    return libra_constraints(libra) == canon["constraints"]


def relaxation_needed(canon, libra):
    """Does the CANONICAL constraint have to be widened for LIBRA's values to pass?

    Returns (change_type, human description). Direction matters: an absent bound is an UNBOUNDED
    one, so `maxLength 100` on the LIBRA side against no maxLength in canonical means canonical is
    already the more permissive of the two and needs no change. A LIBRA bound that is the same or
    tighter is likewise not a schema change — that rule simply belongs in the LIBRA validation
    rules. Only where canonical is demonstrably the narrower side is a relaxation real; where the
    sheet is silent about a bound canonical enforces, no rule here can adjudicate it, so it is
    handed back for review rather than guessed at.
    """
    c, l = canon["constraints"], libra_constraints(libra)

    canon_enum, libra_enum = c.get("enum"), l.get("enum")
    if canon_enum and (not libra_enum or set(libra_enum) - set(canon_enum)):
        allowed = "/".join(map(str, canon_enum))
        if libra_enum:
            supplies = "/".join(map(str, libra_enum))
        elif libra.get("values"):
            supplies = libra["values"]
        else:
            supplies = "other codes documented in the sheet"
        return CH_RELAX_ENUM, (f"drop or extend the enum {allowed} — LIBRA supplies {supplies}")

    if c.get("type") != l.get("type") and c.get("type") and l.get("type"):
        return CH_REVIEW_CONSTRAINT, f"type differs — LIBRA {l['type']} vs canonical {c['type']}"

    if c.get("$ref") != l.get("$ref") and (c.get("$ref") or l.get("$ref")):
        return CH_REVIEW_CONSTRAINT, (f"$ref differs — LIBRA {l.get('$ref') or 'inline'} vs "
                                      f"canonical {c.get('$ref') or 'inline'}")

    wider, unbounded = [], []
    for key, libra_is_wider in (("maxLength", True), ("maximum", True), ("minItems", True),
                                ("minLength", False), ("minimum", False)):
        if key not in c:
            continue                      # canonical is unbounded here — already the wider side
        if key not in l:
            unbounded.append(f"{key} {c[key]}")
        elif (l[key] > c[key]) if libra_is_wider else (l[key] < c[key]):
            wider.append(f"{key} to {l[key]} (canonical {c[key]})")
    if wider:
        return CH_RELAX_CONSTRAINT, "widen " + "; ".join(wider)

    if unbounded:
        return CH_REVIEW_CONSTRAINT, ("canonical bounds " + "; ".join(unbounded)
                                      + " where the sheet states no limit — confirm LIBRA values "
                                        "fit before deciding")

    if c.get("pattern") and not l.get("pattern"):
        return CH_REVIEW_CONSTRAINT, ("canonical enforces a pattern the sheet does not describe — "
                                      "confirm LIBRA values match it")

    return CH_LIBRA_RULE, ("Canonical already permits LIBRA's values; the sheet's tighter rule "
                           "belongs in the LIBRA validation rules")


def container_of(path):
    """Readable owner of a leaf: the jsonpath parent with the `$.migratedCase.` root stripped."""
    parent = path.rpartition(".")[0]
    return parent.replace("$.migratedCase", "").lstrip(".") or "migratedCase"


def funcapp_clause(xhibit_status, action, name):
    """The func-app sentence in change_detail.

    Always phrased as work on the NEW LIBRA schema. The existing XHIBIT schema is never modified —
    the gate gains a source-system-selected second schema — so this never says "relax".
    """
    if action == GATE_OUT_OF_SCOPE:
        return "Func-app: below the gate's validation depth — no change"
    if action == GATE_OMIT:
        if xhibit_status in (FUNC_REQUIRED, FUNC_OPTIONAL):
            return (f"Func-app: the XHIBIT gate schema declares {name} "
                    f"({xhibit_status}) — the new LIBRA schema must OMIT it, so do not carry the "
                    "entry across when authoring that file; XHIBIT's own file is unchanged")
        return f"Func-app: nothing to do — LIBRA does not supply {name}"
    if action == GATE_REQUIRE:
        return (f"Func-app: declare and require {name} in the new LIBRA schema — the sheet marks "
                "it mandatory for every LIBRA case type; XHIBIT's own file is unchanged")
    return (f"Func-app: declare {name} as optional in the new LIBRA schema — the generated "
            "caseDetails is closed (additionalProperties:false), so an undeclared field is "
            "rejected at the gate; XHIBIT's own file is unchanged")


# --------------------------------------------------------------------------------------
# The change decision — one row in, (change_required, change_type, change_detail) out
# --------------------------------------------------------------------------------------

def decide(path, canon, libra, renamed_to, status, xhibit_status, gate_action, mapping,
           parent_closed=False):
    name = canon["name"] if canon else libra["name"]
    container = container_of(path)
    func = funcapp_clause(xhibit_status, gate_action, name)

    # --- a field LIBRA introduces -------------------------------------------------------
    if canon is None:
        tier, pcf_field, _pcf_file, _core_field, _core_file, recommendation = mapping
        if tier == T5:
            if not parent_closed:
                return "no", CH_DEFER, f"{recommendation}. {func}"
            # "Do not add yet" is only free if the payload can carry the field harmlessly. Where
            # the canonical parent is CLOSED it cannot: an undeclared property is a terminal 4xx,
            # so deferring the downstream mapping still forces a decision at the schema.
            return "yes", CH_DECLARE_ONLY, (
                f"Canonical: nothing downstream models {name}, but {container} is closed "
                "(additionalProperties:false), so a LIBRA payload carrying it is rejected outright. "
                "Either declare it as an accepted-but-unmapped optional field, or strip it before "
                f"the command call — do NOT map it onward. {recommendation}. {func}")
        change = CH_ADD_FIELD if tier in (T1, T2) else CH_ADD_BLOCKED
        detail = f"Canonical: add {name} to {container} as optional (the object is closed, so an " \
                 f"undeclared field is a terminal 4xx). {recommendation}"
        if tier in (T3, T4):
            gap = "PCFDLRM has no home for it yet, so canonical alone makes it write-only"
            detail = f"{detail}. PCFDLRM: {gap}"
        if gate_action in (GATE_REQUIRE, GATE_DECLARE) or xhibit_status == FUNC_REQUIRED:
            detail = f"{detail}. {func}"
        return "yes", change, detail

    # --- LIBRA supplies the same concept under another name -----------------------------
    if renamed_to:
        return "yes", CH_MAP_RENAME, (
            f"Transformation: LIBRA supplies {renamed_to} (a reference-data code) where canonical "
            f"{container}.{name} expects a resolved UUID — resolve it in the LIBRA transformation "
            f"strategy, not by loosening the canonical type. {func}")

    # --- LIBRA does not supply the field at all -----------------------------------------
    if libra is None:
        if canon.get("alternatives"):
            return "yes", CH_RELAX_COMBINATOR, (
                f"Canonical: {container} requires one of {name}/{'/'.join(canon['alternatives'])} "
                f"via an anyOf branch, and the LIBRA sheet has none of them — drop or "
                f"source-system-scope that branch. {GUARD}. {func}")
        if canon["required"]:
            return "yes", CH_RELAX_REQUIRED, (
                f"Canonical: make {container}.{name} optional — LIBRA never supplies it. "
                f"{GUARD}. {func}")
        return "no", CH_NONE, f"LIBRA does not supply it and canonical already allows that. {func}"

    # --- present on both sides ----------------------------------------------------------
    if status == CANON_REQ_LIBRA:
        return "no", CH_LIBRA_RULE, (
            f"Canonical already permits it; the sheet's mandatory mark for {name} must be "
            f"enforced in the LIBRA validation rules, not the shared schema. {func}")

    if status == CANON_REQ_CANONICAL:
        return "yes", CH_RELAX_REQUIRED, (
            f"Canonical: make {container}.{name} optional — the sheet marks it optional or "
            f"conditionally mandatory for at least one LIBRA case type. {GUARD}. {func}")

    if status == CANON_CONSTRAINT:
        if is_generator_artefact(canon, libra):
            return "no", CH_NONE, ("Generator artefact only (minimum:0 added for N-format "
                                   f"integers) — not a real difference. {func}")
        change, why = relaxation_needed(canon, libra)
        if change == CH_LIBRA_RULE:
            return "no", change, f"{why}. {func}"
        if change == CH_REVIEW_CONSTRAINT:
            return "yes", change, (f"Canonical: {container}.{name} — {why}. If it is relaxed, "
                                   f"guard: {GUARD_TAIL}. {func}")
        return "yes", change, f"Canonical: {why} on {container}.{name}. {GUARD}. {func}"

    return "no", CH_NONE, f"Identical on both sides. {func}"


# --------------------------------------------------------------------------------------
# Downstream verification (PCFDLRM / core / Progression)
# --------------------------------------------------------------------------------------

def schema_property_names(path):
    """Every property name declared anywhere in a JSON Schema file."""
    try:
        doc = json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return set()
    names = set()

    def walk_node(node):
        if isinstance(node, dict):
            if isinstance(node.get("properties"), dict):
                names.update(node["properties"])
            for value in node.values():
                walk_node(value)
        elif isinstance(node, list):
            for value in node:
                walk_node(value)

    walk_node(doc)
    return names


def field_type(path, leaf):
    """Constraint summary for `leaf` in the given schema file."""
    try:
        doc = json.loads(Path(path).read_text(encoding="utf-8"))
    except Exception:
        return ""
    found = []

    def walk_node(node):
        if isinstance(node, dict):
            props = node.get("properties")
            if isinstance(props, dict) and leaf in props and isinstance(props[leaf], dict):
                found.append(props[leaf])
            for value in node.values():
                walk_node(value)
        elif isinstance(node, list):
            for value in node:
                walk_node(value)

    walk_node(doc)
    if not found:
        return ""
    node = found[0]
    bits = []
    for key in ("type", "$ref", "maxLength", "minLength", "maximum", "minimum"):
        if key in node:
            value = node[key]
            if key == "$ref":
                value = str(value).rsplit("/", 1)[-1].rsplit("#", 1)[0]
            bits.append(f"{key}={value}")
    return " ".join(bits)


def core_closure(root_name=PROGRESSION_ROOT):
    """{basename: (property names, required names)} for every schema reachable from the payload root.

    Indexes the WHOLE core repo (all modules, src/ only) and follows $ref by absolute id, so a
    cross-module hop resolves rather than silently truncating the closure. Today the closure is
    entirely within criminal-court-public-model; the module tally is reported so that changing
    becomes visible instead of invisible.

    A field existing somewhere in core is not enough — core also holds outcome, enforcement, SJP
    and design schemas a migrated case never touches. Only what hangs off the payload root counts.
    """
    if not CORE.is_dir():
        return None, {}
    by_path, by_id = {}, {}
    for path in CORE.rglob("*.json"):
        sp = str(path)
        if "/target/" in sp or "/src/" not in sp:
            continue
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        real = os.path.realpath(path)
        by_path[real] = doc
        schema_id = doc.get("id") or doc.get("$id")
        if schema_id:
            by_id.setdefault(schema_id, real)

    def refs_of(doc):
        out = []

        def walk_node(node):
            if isinstance(node, dict):
                if isinstance(node.get("$ref"), str):
                    out.append(node["$ref"])
                for value in node.values():
                    walk_node(value)
            elif isinstance(node, list):
                for value in node:
                    walk_node(value)

        walk_node(doc)
        return out

    root = next((p for p in by_path
                 if os.path.basename(p) == root_name and "criminal-court-public-model" in p), None)
    if root is None:
        return None, {}
    seen, queue = {root}, [root]
    while queue:
        cur = queue.pop()
        for ref in refs_of(by_path.get(cur) or {}):
            base = ref.split("#")[0]
            if not base:
                continue
            nxt = by_id.get(base) if base.startswith("http") else os.path.realpath(
                os.path.join(os.path.dirname(cur), base))
            if nxt and nxt in by_path and nxt not in seen:
                seen.add(nxt)
                queue.append(nxt)

    closure = {}
    for real in seen:
        acc = []

        def walk_node(node):
            if isinstance(node, dict):
                if isinstance(node.get("properties"), dict):
                    acc.append((set(node["properties"]), set(node.get("required", []))))
                for value in node.values():
                    walk_node(value)
            elif isinstance(node, list):
                for value in node:
                    walk_node(value)

        walk_node(by_path[real])
        if acc:
            closure[os.path.basename(real)] = (set().union(*[a[0] for a in acc]),
                                              set().union(*[a[1] for a in acc]))
    modules = {}
    for real in seen:
        try:
            mod = str(Path(real).relative_to(CORE)).split("/")[0]
        except ValueError:
            mod = "?"
        modules[mod] = modules.get(mod, 0) + 1
    return closure, modules


def progression_status(closure, core_field, core_file, fallback_names=(), scope_file=None):
    """(status, where) for one field against the payload closure.

    A curated (core_field, core_file) claim always wins over a name search: a bare name match picks
    an arbitrary schema, which is how `forename`/`surname` once resolved to judicialRole.json and
    came out mandatory for entirely the wrong reason.
    """
    if closure is None:
        return DOWN_UNVERIFIED, f"{core_file}#{core_field}" if core_field else ""
    if core_field and core_file:
        entry = closure.get(core_file)
        if entry and core_field in entry[0]:
            status = PROG_MANDATORY if core_field in entry[1] else PROG_OPTIONAL
            return status, f"{core_file}#{core_field}"
        return PROG_NONE, ""
    for name in fallback_names:
        if not name:
            continue
        if scope_file:
            entry = closure.get(scope_file)
            if entry and name in entry[0]:
                status = PROG_MANDATORY if name in entry[1] else PROG_OPTIONAL
                return status, f"{scope_file}#{name} (name match)"
            continue
        for bn, (props, req) in sorted(closure.items()):
            if name in props:
                status = PROG_MANDATORY if name in req else PROG_OPTIONAL
                return status, f"{bn}#{name} (unscoped name match)"
    return PROG_NONE, ""


def downstream(field, mapping, verified, closure, failures, container=None):
    """(pcfdlrm_field, pcfdlrm_status, progression_field, progression_status) for a LIBRA-added
    field, verifying every curated claim against the checkouts as it goes."""
    _tier, pcf_field, pcf_file, core_field, core_file, _rec = mapping

    if not pcf_field:
        pcf_status = DOWN_MISSING
    elif not verified:
        pcf_status = DOWN_UNVERIFIED
    else:
        leaf = pcf_field.split(".")[-1]
        path = PCF_SCHEMA / pcf_file
        if not path.exists() or leaf not in schema_property_names(path):
            failures.append(f"PCFDLRM: {field} -> {pcf_file}#{leaf}")
            pcf_status = DOWN_UNVERIFIED
        else:
            pcf_status = DOWN_EXISTS if leaf == field else DOWN_RENAMED
            constraints = field_type(path, leaf)
            pcf_field = f"{pcf_file}#{pcf_field}" + (f" ({constraints})" if constraints else "")

    prog_st, prog_where = progression_status(
        closure, core_field, core_file,
        fallback_names=(field, (pcf_field or "").split("#")[-1]),
        scope_file=CONTAINER_CORE.get(container))
    if core_field and core_file and prog_st == PROG_NONE:
        failures.append(f"core: {field} -> {core_file}#{core_field} "
                        "(not in the courtReferral payload closure)")
    return pcf_field or "", pcf_status, prog_where, prog_st


# --------------------------------------------------------------------------------------
# Assembly
# --------------------------------------------------------------------------------------

COLUMNS = ["libra_field", "jsonpath", "container",
           "funcapp_xhibit_status", "funcapp_libra_action", "canonical_field", "canonical_status",
           "pcfdlrm_field", "pcfdlrm_status", "progression_field", "progression_status",
           "change_required", "change_type", "change_detail", "tier", "notes"]

MARKDOWN_COLUMNS = {"notes", "change_detail"}   # the only columns carrying emphasis/backticks


def note_text(canon, libra, status, mapping):
    notes = []
    if canon is None:
        if libra and libra["row"]:
            notes.append(f"LIBRA sheet row {libra['row']}")
        if mapping:
            notes.append(mapping[5])
    else:
        if status == CANON_CONSTRAINT and libra:
            notes.append(f"LIBRA {render(libra['constraints'])} vs canonical "
                         f"{render(canon['constraints'])}")
        if canon["required"] and libra is None:
            notes.append("**required in canonical but absent from the LIBRA sheet — blocker**")
        if canon.get("alternatives"):
            notes.append("part of an anyOf required-branch with "
                         + "/".join(canon["alternatives"]))
    return "; ".join(notes)


def render(constraints):
    if not constraints:
        return "—"
    bits = []
    for key, value in constraints.items():
        if key == "pattern":
            bits.append("pattern")
        elif key == "enum":
            bits.append("enum " + "/".join(map(str, value)))
        elif key == "type":
            bits.append(str(value))
        else:
            bits.append(f"{key} {value}")
    return ", ".join(bits)


def build(libra_path=None, canonical_path=None, funcapp_path=None,
          gate_depth=DEFAULT_GATE_DEPTH):
    libra_doc = json.loads(Path(libra_path or DEFAULT_LIBRA).read_text(encoding="utf-8"))
    canon_doc = json.loads(Path(canonical_path or DEFAULT_CANONICAL).read_text(encoding="utf-8"))
    func_path = Path(funcapp_path or DEFAULT_FUNCAPP)
    if not func_path.exists():
        sys.exit(f"error: {func_path} not found — run flatten-canonical-schema.py against "
                 "stagingdlrm-azure-functions/src/main/resources first (regenerate.sh does)")
    func_doc = json.loads(func_path.read_text(encoding="utf-8"))

    L, _ = walk(libra_doc, ROOT_PROPERTY)
    C, C_objects = walk(canon_doc, ROOT_PROPERTY)
    F, F_objects = walk(func_doc, ROOT_PROPERTY)
    for store in (L, C, F):
        drop_envelope(store)

    verified = PCF_SCHEMA.is_dir()
    if not verified:
        print(f"warning: {PCFDLRM} not found — PCFDLRM claims are UNVERIFIED", file=sys.stderr)
    closure, modules = core_closure()
    if closure is None:
        print(f"warning: {CORE} not found or {PROGRESSION_ROOT} missing — Progression claims are "
              "UNVERIFIED", file=sys.stderr)
    else:
        print(f"payload closure from {PROGRESSION_ROOT}: {len(closure)} schemas, modules={modules}",
              file=sys.stderr)

    rows, matched, failures = [], set(), []

    # --- every canonical field, LIBRA measured against it -------------------------------
    for path, canon in C.items():
        parent, _, name = path.rpartition(".")
        renamed_to = RENAMES.get((parent, name))
        l_path = f"{parent}.{renamed_to}" if renamed_to else path
        libra = L.get(l_path)
        if libra is not None:
            matched.add(l_path)

        status = CANON_RENAMED if (renamed_to and libra) else canonical_status(canon, libra)
        xhibit_status = funcapp_xhibit_status(path, F, F_objects)
        gate_action = funcapp_libra_action(path, libra, gate_depth)
        required, change_type, change_detail = decide(
            path, canon, libra, renamed_to if libra else None, status, xhibit_status, gate_action,
            None)
        rows.append({
            "libra_field": libra["name"] if libra else "",
            "jsonpath": path,
            "container": container_of(path),
            "funcapp_xhibit_status": xhibit_status,
            "funcapp_libra_action": gate_action,
            "canonical_field": name,
            "canonical_status": status,
            # Already in the canonical schema and exercised by XHIBIT in production, so both
            # downstream hops are taken as given. The LIBRA-driven risk on these rows is the
            # RELAXATION, which change_type carries (relax-* => an XHIBIT rule is now needed,
            # libra-rule-only => a LIBRA rule is).
            "pcfdlrm_field": "",
            "pcfdlrm_status": DOWN_FLOWING,
            "progression_field": "",
            "progression_status": PROG_ASSUMED,
            "change_required": required,
            "change_type": change_type,
            "change_detail": change_detail,
            "tier": "",
            "notes": note_text(canon, libra, status, None),
        })

    # --- fields LIBRA adds --------------------------------------------------------------
    added = [(p, e) for p, e in L.items() if p not in matched and p not in C]
    unmapped = sorted({e["name"] for _p, e in added if e["name"] not in MAPPING})
    if unmapped:
        sys.exit(f"error: no curated mapping for {unmapped} — update MAPPING")
    stale = sorted(set(MAPPING) - {e["name"] for _p, e in added})
    if stale:
        print(f"warning: MAPPING has entries no longer in the LIBRA schema: {stale}",
              file=sys.stderr)

    for path, libra in added:
        mapping = MAPPING[libra["name"]]
        xhibit_status = funcapp_xhibit_status(path, F, F_objects)
        gate_action = funcapp_libra_action(path, libra, gate_depth)
        pcf_field, pcf_status, prog_field, prog_status = downstream(
            libra["name"], mapping, verified, closure, failures, container_of(path))
        parent_closed = (C_objects.get(path.rpartition(".")[0]) or {}).get("closed", False)
        required, change_type, change_detail = decide(
            path, None, libra, None, CANON_ADDED, xhibit_status, gate_action, mapping,
            parent_closed)
        rows.append({
            "libra_field": libra["name"],
            "jsonpath": path,
            "container": container_of(path),
            "funcapp_xhibit_status": xhibit_status,
            "funcapp_libra_action": gate_action,
            "canonical_field": "",
            "canonical_status": CANON_ADDED,
            "pcfdlrm_field": pcf_field,
            "pcfdlrm_status": pcf_status,
            "progression_field": prog_field,
            "progression_status": prog_status,
            "change_required": required,
            "change_type": change_type,
            "change_detail": change_detail,
            "tier": mapping[0],
            "notes": note_text(None, libra, CANON_ADDED, mapping),
        })

    if failures:
        sys.exit("error: curated downstream claims no longer hold:\n  " + "\n  ".join(failures))

    # Work first, then by tier, then by depth — so the rows that need doing sort to the top.
    rows.sort(key=lambda r: (r["change_required"] != "yes", TIER_ORDER[r["tier"]],
                             r["jsonpath"].count("."), r["jsonpath"]))
    return fill_na(rows)


def fill_na(rows):
    """Replace structurally-empty cells with an explicit marker. Applied after sorting."""
    for row in rows:
        for col in NA_FILLED_COLUMNS:
            if not row[col]:
                row[col] = NA
        if not row["tier"]:
            row["tier"] = TIER_NA
    return rows


def plain(text):
    """Strip markdown emphasis — CSV readers show it literally.

    Applied ONLY to prose columns: a blanket strip would also eat the `*` in `defendants[*]`,
    silently corrupting every array jsonpath.
    """
    return re.sub(r"\*\*|`", "", str(text))


def main():
    global PCFDLRM, CORE, PCF_SCHEMA

    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--format", choices=("markdown", "csv"), default="markdown")
    ap.add_argument("--libra", help="generated LIBRA schema (default: the committed one)")
    ap.add_argument("--canonical", help="flattened canonical schema (default: the committed one)")
    ap.add_argument("--funcapp", help="flattened func-app schema (default: the committed one)")
    ap.add_argument("--pcfdlrm", default=str(PCFDLRM),
                    help="cpp-context-prosecution-casefile-dlrm checkout")
    ap.add_argument("--core", default=str(CORE), help="cpp.platform.core.domain checkout")
    ap.add_argument("--funcapp-libra-depth", choices=sorted(GATE_DEPTHS),
                    default=DEFAULT_GATE_DEPTH,
                    help="how deep the new LIBRA gate schema is assumed to validate, which decides "
                         "funcapp_libra_action. 'case-details' (default) mirrors the depth the "
                         "XHIBIT gate uses today; 'full' assumes the generated LIBRA schema is used "
                         "at its own depth")
    ap.add_argument("--changes-only", action="store_true",
                    help="emit only the rows where change_required is yes")
    ap.add_argument("--out-dir", default=".",
                    help="directory to write the CSV into (default: current directory)")
    ap.add_argument("--out", nargs="?", const="",
                    help="write CSV instead of stdout; bare --out uses --out-dir, "
                         "or give an explicit path")
    args = ap.parse_args()

    PCFDLRM = Path(args.pcfdlrm)
    CORE = Path(args.core)
    PCF_SCHEMA = PCFDLRM / "pcfdlrm-domain/pcfdlrm-domain-value-schema/src/main/resources/json/schema"

    rows = build(args.libra, args.canonical, args.funcapp, args.funcapp_libra_depth)
    total = len(rows)
    if args.changes_only:
        rows = [r for r in rows if r["change_required"] == "yes"]

    if args.format == "csv" or args.out is not None:
        # utf-8-sig: Excel needs the BOM to read the em dashes as UTF-8 rather than mojibake.
        # Values are also guarded against being read as formulas.
        clean = []
        for r in rows:
            row = {c: (plain(r[c]) if c in MARKDOWN_COLUMNS else str(r[c])) for c in COLUMNS}
            for c, v in row.items():
                if v[:1] in ("=", "+", "-", "@"):
                    row[c] = "'" + v
            clean.append(row)
        if args.out is not None:
            out = Path(args.out) if args.out else Path(args.out_dir) / DEFAULT_NAME
            out.parent.mkdir(parents=True, exist_ok=True)
            with out.open("w", encoding="utf-8-sig", newline="") as fh:
                w = csv.DictWriter(fh, fieldnames=COLUMNS)
                w.writeheader()
                w.writerows(clean)
            print(f"WROTE: {out}   {len(clean)} rows x {len(COLUMNS)} columns")
        else:
            w = csv.DictWriter(sys.stdout, fieldnames=COLUMNS)
            w.writeheader()
            w.writerows(clean)
    else:
        print("| " + " | ".join(COLUMNS) + " |")
        print("|" + "|".join(["---"] * len(COLUMNS)) + "|")
        code_columns = ("libra_field", "jsonpath", "container", "canonical_field", "pcfdlrm_field")
        for r in rows:
            cells = [str(r[c]).replace("|", "\\|") for c in COLUMNS]
            cells = [f"`{c}`" if col in code_columns and c and c != NA else c
                     for col, c in zip(COLUMNS, cells)]
            print("| " + " | ".join(cells) + " |")

    tally = {}
    for r in rows:
        for col in ("change_type", "funcapp_xhibit_status", "funcapp_libra_action",
                    "canonical_status"):
            tally.setdefault(col, {}).setdefault(r[col], 0)
            tally[col][r[col]] += 1
    changes = sum(1 for r in rows if r["change_required"] == "yes")
    print(f"\n<!-- {len(rows)} of {total} rows; {changes} need a change", file=sys.stderr)
    for col, counts in tally.items():
        print(f"     {col}: {dict(sorted(counts.items()))}", file=sys.stderr)
    print("-->", file=sys.stderr)


if __name__ == "__main__":
    main()
