#!/usr/bin/env python3
"""Flatten a multi-file stagingDLRM schema set into one self-contained document.

Used for both schema sets the pipeline validates against, which is why --source/--root/--out are
parameters rather than constants:

    CANONICAL  stagingdlrm-domain-value-schema — one JSON Schema per file, wired together by
               absolute `$id` URLs (resolved at build time against a catalog generated by
               catalog-generation-plugin). Rooted at migrated-case-submission.json.
    FUNC-APP   stagingdlrm-azure-functions/src/main/resources — the Function App's own local
               copies, wired together by bare relative filenames instead. Rooted at
               stagingdlrm.case-submission.json.

Either form is impossible to diff directly against a single-document schema, so this script
inlines every in-module `$ref` into `#/definitions/<name>`. Both ref styles are resolved, and the
func-app's copies are indexed by filename as well as `$id` because the two disagree there
(pcf-prosecutor.json declares `"id": "prosecutor.json"` but is $ref'd by its filename).

Reads from src/main/resources (the git checkout), never target/ or ~/.m2 — build output can lag
behind the source.

Definition names are derived from each schema's `$id` basename (kebab-case -> camelCase), with a
small alias table where a filename differs from the name the analysis docs use
(e.g. case-marker -> caseMarkers).

Refs to schemas OUTSIDE the module (justice.gov.uk core: date, date-time, uuid) cannot be
resolved from this repo. They are hoisted into local stub definitions, flagged as external in
their description, and listed in the report — so the diff compares "both sides say date" rather
than reporting a spurious constraint difference. Pass --core to resolve them for real.

Usage:
    python3 tools/schema-gen/flatten-canonical-schema.py                    # canonical
    python3 tools/schema-gen/flatten-canonical-schema.py \
        --source stagingdlrm-azure-functions/src/main/resources \
        --root stagingdlrm.case-submission.json \
        --out schema/canonical/staging-dlrm-funcapp-flattened.json          # func-app
"""

import argparse
import json
import os
import re
import sys
from collections import OrderedDict
from pathlib import Path

REPO = Path(__file__).resolve().parents[2]
DEFAULT_SOURCE = REPO / ("stagingdlrm-domain/stagingdlrm-domain-value-schema"
                         "/src/main/resources/json/schema")
DEFAULT_NAME = "staging-dlrm-canonical-flattened.json"
DEFAULT_ROOT = "migrated-case-submission.json"

MODULE_PREFIX = "http://cpp.moj.gov.uk/stagingdlrm"

# Schemas this module $refs but does not contain (justice.gov.uk core: date, date-time, uuid) live
# in the shared core-domain repo. Indexing it by $id lets those refs resolve for real instead of
# being stubbed, so a comparison can check their patterns rather than just their names.
DEFAULT_CORE = Path(os.path.expanduser("~/work/repo/cpp.platform.core.domain"))

# Canonical filename -> the name the analysis docs use, where they differ.
NAME_ALIASES = {"caseMarker": "caseMarkers"}

# External schemas this module refs but does not contain.
EXTERNAL_ALIASES = {
    "date": "date",
    "date-time": "dateTime",
    "uuid": "uuid",
}


def camel(text):
    parts = re.split(r"[-_]", text)
    return parts[0] + "".join(p[:1].upper() + p[1:] for p in parts[1:])


def definition_name(schema_id):
    base = schema_id.rstrip("/").rsplit("/", 1)[-1]
    if base.endswith(".json"):
        base = base[:-5]
    name = camel(base)
    return NAME_ALIASES.get(name, name)


def load_external(core_root):
    """{schema $id: document} for every schema in the core-domain repo."""
    by_id = {}
    if not core_root or not Path(core_root).is_dir():
        return by_id
    for path in Path(core_root).rglob("*.json"):
        if "target" in path.parts or "/src/" not in str(path.parent) + "/":
            continue
        try:
            doc = json.loads(path.read_text(encoding="utf-8"))
        except Exception:
            continue
        schema_id = doc.get("id") or doc.get("$id")
        if schema_id:
            by_id.setdefault(schema_id, doc)
    return by_id


def load(source):
    """Return ({schema_id: (definition name, document, path)}, {filename: schema_id}, collisions).

    The filename index exists because the two schema sets wire themselves up differently: the
    canonical module uses absolute `$id` URLs, while the func-app's local copies use bare relative
    refs — and there they do not always agree with the `$id` (pcf-prosecutor.json declares
    `"id": "prosecutor.json"` but is $ref'd by its filename). Indexing both means a ref can be
    resolved whichever of the two it names.
    """
    by_id, by_file, collisions = OrderedDict(), {}, []
    for path in sorted(source.rglob("*.json")):
        doc = json.loads(path.read_text(encoding="utf-8"))
        schema_id = doc.get("id") or doc.get("$id")
        if not schema_id:
            continue
        name = definition_name(schema_id)
        if schema_id in by_id:
            collisions.append((schema_id, path))
            continue
        by_id[schema_id] = (name, doc, path)
        by_file.setdefault(path.name, schema_id)
    return by_id, by_file, collisions


def flatten(source, root_file, core_root=None):
    by_id, by_file, collisions = load(source)
    external_by_id = load_external(core_root)
    if not by_id:
        sys.exit(f"error: no schemas with an $id found under {source}")

    definitions = OrderedDict()
    hoisted, external, unresolved = OrderedDict(), OrderedDict(), []
    resolved = OrderedDict()   # external name -> the real node pulled from core-domain

    def local_ref(value):
        """Is this a same-module ref (an absolute module URL, or a sibling filename)?"""
        base = value.partition("#")[0]
        if not base:
            return False                      # already a local #/... pointer
        return (base.startswith(MODULE_PREFIX)
                or (not base.startswith("http") and (base in by_id or base in by_file)))

    def holder_for(base):
        return by_id.get(base) or by_id.get(by_file.get(base, ""))

    def rewrite(node):
        """Replace every in-module $ref with a local #/definitions/<name> pointer."""
        if isinstance(node, list):
            return [rewrite(v) for v in node]
        if not isinstance(node, dict):
            return node

        out = OrderedDict()
        for key, value in node.items():
            if key == "$ref" and isinstance(value, str) and (value.startswith("http")
                                                             or local_ref(value)):
                base, _, fragment = value.partition("#")
                if local_ref(value):
                    if fragment:
                        # e.g. pcf-definitions.json#/email or #/definitions/channel — the
                        # pointed-at node is hoisted under its own leaf name.
                        leaf = fragment.strip("/").split("/")[-1]
                        holder = holder_for(base)
                        if holder is None:
                            unresolved.append(value)
                            out[key] = value
                            continue
                        target = holder[1]
                        for step in [s for s in fragment.strip("/").split("/") if s]:
                            target = target.get(step, {}) if isinstance(target, dict) else {}
                        if not target:
                            unresolved.append(value)
                            out[key] = value
                            continue
                        hoisted[leaf] = rewrite(target)
                        out[key] = f"#/definitions/{leaf}"
                    else:
                        holder = holder_for(base)
                        if holder is None:
                            unresolved.append(value)
                            out[key] = value
                            continue
                        out[key] = f"#/definitions/{holder[0]}"
                else:
                    leaf = fragment.strip("/").split("/")[-1] if fragment else base
                    name = EXTERNAL_ALIASES.get(leaf, camel(leaf))
                    holder = external_by_id.get(base)
                    node = None
                    if holder is not None:
                        node = holder
                        for step in [s for s in fragment.strip("/").split("/") if s]:
                            node = node.get(step) if isinstance(node, dict) else None
                            if node is None:
                                break
                    external[name] = (value, node is not None)
                    if node is not None:
                        resolved[name] = node
                    out[key] = f"#/definitions/{name}"
            else:
                out[key] = rewrite(value)
        return out

    root_id = None
    for schema_id, (name, doc, path) in by_id.items():
        if path.name == root_file:
            root_id = schema_id
        # A file that only holds shared sub-definitions (pcf-definitions.json) contributes via
        # hoisting, not as a definition of its own. Everything carrying an actual schema keyword
        # is emitted — including bare scalar types like migrationSourceSystemName.json (a string
        # enum with no `properties`).
        if not any(k in doc for k in ("properties", "type", "enum", "oneOf", "anyOf", "allOf",
                                      "$ref", "items")):
            continue
        entry = OrderedDict()
        for key, value in doc.items():
            if key in ("$schema", "id", "$id"):
                continue
            entry[key] = rewrite(value)
        definitions[name] = entry

    if root_id is None:
        sys.exit(f"error: root {root_file!r} not found under {source}")

    for leaf, node in hoisted.items():
        definitions.setdefault(leaf, node)
    for name, (original, was_resolved) in external.items():
        if was_resolved:
            entry = OrderedDict(resolved[name])
            entry["description"] = (
                f"Resolved from {original} in the core-domain repo; "
                "not defined in stagingdlrm-domain-value-schema.")
            definitions.setdefault(name, entry)
        else:
            definitions.setdefault(name, OrderedDict([
                ("type", "string"),
                ("description", f"EXTERNAL, UNRESOLVED — {original}; core-domain repo not found."),
            ]))

    root_name = by_id[root_id][0]
    schema = OrderedDict([
        ("$schema", "http://json-schema.org/draft-04/schema#"),
        ("id", "http://cpp.moj.gov.uk/stagingdlrm/json/schemas/canonical-flattened.json"),
        ("type", "object"),
        ("description",
         f"Flattened view of the canonical stagingDLRM schema, rooted at {root_file}. Generated "
         "by tools/schema-gen/flatten-canonical-schema.py from "
         "stagingdlrm-domain-value-schema/src/main/resources/json/schema. Not used at runtime — "
         "this exists only so the multi-file canonical schema can be diffed against a "
         "single-document one. Do not hand-edit."),
        ("$ref", f"#/definitions/{root_name}"),
        ("definitions", definitions),
    ])
    return schema, {"files": len(by_id), "collisions": collisions, "root": root_name,
                    "hoisted": list(hoisted), "external": external,
                    "external_files": len(external_by_id),
                    "unresolved": sorted(set(unresolved))}


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("--source", default=str(DEFAULT_SOURCE),
                    help="the multi-file canonical schema directory to flatten")
    ap.add_argument("--root", default=DEFAULT_ROOT, help="filename of the entry-point schema")
    ap.add_argument("--core", default=str(DEFAULT_CORE),
                    help="core-domain repo, used to resolve justice.gov.uk refs for real")
    ap.add_argument("--out-dir", default=".",
                    help="directory to write the flattened schema into (default: current directory)")
    ap.add_argument("--out", help="explicit output path; overrides --out-dir")
    ap.add_argument("--dry-run", action="store_true")
    args = ap.parse_args()

    source = Path(args.source)
    if not source.is_dir():
        sys.exit(f"error: not a directory: {source}")
    if "target" in source.parts:
        print(f"warning: reading build output ({source}) — prefer src/main/resources", file=sys.stderr)

    schema, info = flatten(source, args.root, args.core)

    if not args.dry_run:
        out = Path(args.out) if args.out else Path(args.out_dir) / DEFAULT_NAME
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(schema, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")

    shown = args.out if args.out else str(Path(args.out_dir) / DEFAULT_NAME)
    print(f"{'DRY RUN' if args.dry_run else 'WROTE'}: {shown}")
    print(f"  source files: {info['files']}   root: {info['root']}"
          f"   definitions: {len(schema['definitions'])}")
    if info["hoisted"]:
        print(f"  hoisted shared sub-definitions ({len(info['hoisted'])}): "
              + ", ".join(info["hoisted"]))
    if info["external"]:
        ok = sum(1 for _, was in info["external"].values() if was)
        print(f"  EXTERNAL refs ({len(info['external'])}): {ok} resolved from core-domain "
              f"({info['external_files']} core schemas indexed), {len(info['external'])-ok} stubbed")
        for name, (original, was) in info["external"].items():
            print(f"    {'OK  ' if was else 'STUB'} {name} <- {original}")
    if info["collisions"]:
        print(f"  $id COLLISIONS ({len(info['collisions'])}):")
        for schema_id, path in info["collisions"]:
            print(f"    {schema_id} ({path})")
    if info["unresolved"]:
        print(f"  UNRESOLVED refs ({len(info['unresolved'])}):")
        for ref in info["unresolved"]:
            print(f"    {ref}")


if __name__ == "__main__":
    main()
