<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>
    <parent>
        <artifactId>stagingdlrm-viewstore</artifactId>
        <groupId>uk.gov.moj.cpp.stagingdlrm</groupId>
        <version>17.104.33-LIBRA1-SNAPSHOT</version>
    </parent>

    <artifactId>stagingdlrm-viewstore-liquibase</artifactId>
    <name>stagingdlrm-viewstore-liquibase</name>

    <properties>
        <sonar.skip>true</sonar.skip>
    </properties>

    <dependencies>
        <dependency>
            <groupId>org.liquibase</groupId>
            <artifactId>liquibase-core</artifactId>
        </dependency>
    </dependencies>
</project>
