<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <artifactId>stagingdlrm-parent</artifactId>
        <groupId>uk.gov.moj.cpp.stagingdlrm</groupId>
        <version>17.103.41-PEG-2848-SNAPSHOT</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>

    <artifactId>stagingdlrm-domain</artifactId>
    <packaging>pom</packaging>

    <modules>
        <module>stagingdlrm-domain-event</module>
        <module>stagingdlrm-domain-aggregate</module>
        <module>stagingdlrm-domain-transformations</module>
        <module>stagingdlrm-domain-value-schema</module>
    </modules>

</project>
